### ISSUE TITLE
[tests] test the test suite from a clean checkout

### ISSUE THREAD

**Issue by bmr-cymru** [bmr-cymru/boom#28]
Since the work to move test case execution into sandboxed test fixtures is now complete, it should be possible to run the test suite on an arbitrary system from a clean checkout of the upstream source.

**Comment by bmr-cymru** [comment]
This is failing for now:

```
======================================================================
ERROR: test_BootEntry (tests.bootloader_tests.BootEntryBasicTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/root/boom/tests/bootloader_tests.py", line 207, in test_BootEntry
    be = BootEntry(title="title", machine_id="ffffffff")
  File "/root/boom/boom/bootloader.py", line 1416, in __init__
    self.__match_host_profile()
  File "/root/boom/boom/bootloader.py", line 1175, in __match_host_profile
    hps = find_host_profiles(Selection(machine_id=machine_id))
  File "/root/boom/boom/hostprofile.py", line 331, in find_host_profiles
    load_host_profiles()
  File "/root/boom/boom/hostprofile.py", line 206, in load_host_profiles
    load_profiles_for_class(HostProfile, "Host", profiles_path, "host")
  File "/root/boom/boom/_boom.py", line 865, in load_profiles_for_class
    profile_files = listdir(profiles_path)
OSError: [Errno 2] No such file or directory: '/boot/boom/hosts'
```

(same error affects several other test cases - just a case of setting `BOOM_BOOT_PATH`?)

```
======================================================================
ERROR: test_edit_entry_with_add_del_opts (tests.command_tests.CommandTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/root/boom/tests/command_tests.py", line 770, in test_edit_entry_with_add_del_opts
    profile=osp)
  File "/root/boom/boom/command.py", line 451, in create_entry
    architecture=architecture, allow_no_dev=allow_no_dev)
  File "/root/boom/boom/bootloader.py", line 1420, in __init__
    check_root_device(self.bp.root_device)
  File "/root/boom/boom/bootloader.py", line 235, in check_root_device
    raise BoomRootDeviceError("Device '%s' not found." % dev)
BoomRootDeviceError: Device '/dev/vg_hex/root' not found.
```

Test suite relies on specific devices in `/dev`, which it shouldn't. These are only needed for presence checks: they are never modified or opened for writing by the suite. A few possibilities:

* Run everything with `nodev=True` (reduces coverage)
* Pick a random block device or logical volume, and use `@unittest.skip()` decorators if none is available
* Mock up a `dev/` directory under the test sandbox from the fixture methods, and populate it with known (fake) device entries. This is probably cleanest but it would mean making the boom device path configurable.

```
ERROR: test_show_legacy_default (tests.command_tests.CommandHelperTests)
Test the show_legacy() command helper.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/root/boom/tests/command_tests.py", line 185, in test_show_legacy_default
    boom.command.show_legacy()
  File "/root/boom/boom/command.py", line 1432, in show_legacy
    [print(decorator(be)) for be in bes]
  File "/root/boom/boom/legacy.py", line 336, in __str__
    return grub1_fmt % (self.be.title, _get_grub1_device(),
  File "/root/boom/boom/legacy.py", line 83, in _get_grub1_device
    raise BoomLegacyLoaderError("Could not execute grub1 shell.")
NameError: global name 'BoomLegacyLoaderError' is not defined
```

Error in legacy loader error path - simple fix?

```
======================================================================
FAIL: test__create_cmd_auto_machine_id (tests.command_tests.CommandTests)
Test the _create_cmd() handler with automatic machine_id.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/root/boom/tests/command_tests.py", line 1262, in test__create_cmd_auto_machine_id
    self.assertNotEqual(r, 1)
AssertionError: 1 == 1

======================================================================
FAIL: test__create_cmd_version_from_uts (tests.command_tests.CommandTests)
Test the _create_cmd() handler with missing version, and the
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/root/boom/tests/command_tests.py", line 1244, in test__create_cmd_version_from_uts
    self.assertNotEqual(r, 1)
AssertionError: 1 == 1
```

Not clear what's going on with these two. These should both default the missing value from the environment.

**Comment by bmr-cymru** [comment]
This class of errors:

```
======================================================================
ERROR: test_BootEntry (tests.bootloader_tests.BootEntryBasicTests)
----------------------------------------------------------------------
[...]
  File "/root/boom/boom/_boom.py", line 865, in load_profiles_for_class
    profile_files = listdir(profiles_path)
OSError: [Errno 2] No such file or directory: '/boot/boom/hosts'
```

Is fixed by moving the `BootEntryBasicTests` class to use a sandbox fixture, and to not refer to the default boom paths in `/boot`.

```
commit 45246bed587d9df55fb745dbb885f41005f5410f
Author: Bryn M. Reeves <bmr@redhat.com>
Date:   Thu Feb 28 12:56:05 2019 +0000

    tests: add sandbox fixtures to BootEntryBasicTests
    
    Add a boot/ sandbox fixture to the BootEntryBasicTests class to
    prevent the test suite trying to poke random paths in the host's
    /boot:
    
    ======================================================================
    ERROR: test_BootEntry (tests.bootloader_tests.BootEntryBasicTests)
    ----------------------------------------------------------------------
    Traceback (most recent call last):
      File "/root/boom/tests/bootloader_tests.py", line 207, in test_BootEntry
        be = BootEntry(title="title", machine_id="ffffffff")
      File "/root/boom/boom/bootloader.py", line 1416, in __init__
        self.__match_host_profile()
      File "/root/boom/boom/bootloader.py", line 1175, in __match_host_profile
        hps = find_host_profiles(Selection(machine_id=machine_id))
      File "/root/boom/boom/hostprofile.py", line 331, in find_host_profiles
        load_host_profiles()
      File "/root/boom/boom/hostprofile.py", line 206, in load_host_profiles
        load_profiles_for_class(HostProfile, "Host", profiles_path, "host")
      File "/root/boom/boom/_boom.py", line 865, in load_profiles_for_class
        profile_files = listdir(profiles_path)
    OSError: [Errno 2] No such file or directory: '/boot/boom/hosts'
    
    Related: #28
    
    Signed-off-by: Bryn M. Reeves <bmr@redhat.com>
```

**Comment by bmr-cymru** [comment]
```
FAILED (failures=2, errors=19, skipped=1)
```

**Comment by bmr-cymru** [comment]
This one:

```
======================================================================
ERROR: test_show_legacy_default (tests.command_tests.CommandHelperTests)
Test the show_legacy() command helper.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/root/src/git/boom/tests/command_tests.py", line 185, in test_show_legacy_default
    boom.command.show_legacy()
  File "/root/src/git/boom/boom/command.py", line 1432, in show_legacy
    [print(decorator(be)) for be in bes]
  File "/root/src/git/boom/boom/legacy.py", line 336, in __str__
    return grub1_fmt % (self.be.title, _get_grub1_device(),
  File "/root/src/git/boom/boom/legacy.py", line 83, in _get_grub1_device
    raise BoomLegacyFormatError("Could not execute grub1 shell.")
BoomLegacyFormatError: Could not execute grub1 shell.
```

Needs a predicate decorator to skip the test when the grub1 shell is unavailable. It's correct for this API call to throw this exception when that is the case.
